### PR TITLE
Define new hooks for ActiveRecord::Reflection::AssociationReflection

### PR DESCRIPTION
**Pull request by lowjoel**
Needed for me to do reflection on reflection properties.

I've not managed to run the tests yet. The tests here are complete stabs in the dark...

### CODE REVIEW

**Comment by lowjoel** [comment]
@ronen Finally got postgresql/ruby2.2/AR4.2 tested on Windows. Not the full matrix, but at least it's some testing.

**Comment by lowjoel** [comment]
@ronen Any comments on this? I've no clue why coverage goes down on those, I didn't remove anything...

**Comment by ronen** [comment]
@lowjoel  [sorry for the slow response, my (limited) schema_plus time has been mostly taken up by a small flurry of bug reports, hadn't had a chance to look into this until now.]

I'm concerned that the stack is being wrapped around an undocumented internal method -- and given where that method is called, `after` and `around`, and `implement` middleware callbacks wouldn't have expected semantics.

I think for your inverse-checking gem you want to be able to hook into the declaration of associations (rather than, say, looking up associations via `reflect_on_association`).   So I think the hook should be named something like `Model::Association::Declare`.   And unfortunately looking at the AR source I don't see just one place it can be put -- I think there'd need to be a wrapper around all four of `belongs_to`, `has_one`, and `has_many` and `has_and_belongs_to_many`, along the lines of:

```ruby
def belongs_to(name, scope=nil, options={})
  SchemaMonkey::Middleware::Model::Association::Declare.start model:self, name: name, scope: scope, options: options, type: :belongs_to do |env|
    super env.name, env.scope, env.options
  end
end
```
and similarly for the others.

Given that, for your inverse-checking gem, I think you'd use an `after` middleware callback, something like:

```ruby
def after(env)
  return if env.type == :has_and_belongs_to_many  # no :inverse_of needed for HABTM
  reflection = env.model.reflections[env.name]
  # ...rest of your logic here..
end
```

Does this make sense?

**Comment by lowjoel** [comment]
Good idea. That was the callsite I identified needing hooking, so that was the first thing I came up with. I'll change it.

**Comment by lowjoel** [comment]
@ronen updated, how does this look? I'll port my gem over now.

**Comment by ronen** [comment]
@lowjoel for the stack to allow middleware to examine (and potentially modify) the arguments, they need to be captured in the `env` object, and passed to the underlying implementation from the `env` object.  Also typically middleware will need to know which model this is acting on.   So the overrided method needs to have this form:

```ruby
def belongs_to(name, scope=nil, options={})
  SchemaMonkey::Middleware::Model::Association::Declare.start model:self, name: name, scope: scope, options: options, type: :belongs_to do |env|   # captures model and all args in env
    super env.name, env.scope, env.options               # call implementation using values from env (potentially modified by middleware)
  end
end
```

**Comment by lowjoel** [comment]
Yeah I realised after pushing that self isn't captured. Spent a lot of time messing around with gemfiles

**Comment by lowjoel** [comment]
The problem I foresee is that across different versions of Rails, the parameter list might change and the gem will break for some versions but not others. Declaring the list of parameters in the environment isn't sustainable...

I'm fixing the PR now.

**Comment by lowjoel** [comment]
@ronen pushed. I'm not sure if you're going to bump the gem to 0.3

**Comment by ronen** [comment]
@lowjoel good catch adding `&extensions` -- I had forgotten about that!

Care to update the README too?

Re parameter list changing across different versions of AR:  Yeah, not much can be done about that -- we need to expose all the args to the middleware in the stack.  As versions change, schema_plus_core is going to accumulate version-specific conditionals and other cruft, (just as schema_plus 1.x did).  But at least all that ugliness will (hopefully) be hidden in schema_plus_core so all the other gems would stay cleaner.  

And yes, this will be a minor version bump.

**Comment by lowjoel** [comment]
Pushed, have a look.

**Comment by ronen** [comment]
> Pushed, have a look.

@lowjoel Did you mean to push something new?

**Comment by lowjoel** [comment]
crap, push was rejected, sorry. really pushed now.

**Comment by ronen** [comment]
Cool, thanks.  Merging.

**Comment by ronen** [comment]
...and I've released 0.3.0

**Comment by lowjoel** [comment]
:+1: https://github.com/lowjoel/schema_plus_association_inverses

**Pull request merged**
