### PR TITLE
Allow installing on a Rails 5 app

### PR DESCRIPTION
**Pull request by adamico**

### CODE REVIEW

**Comment by ronen** [comment]
@adamico I can easily imagine that this doesn't work as is with AR 5, but I haven't had a chance to try it.  Have you verified that it doesn't work?

**Comment by adamico** [comment]
@ronen the Rails 5 app using the schema_plus_view gem has a green test suite, so I'm quite confident it works.

**Comment by ronen** [comment]
@adamico Sorry i was confused, i thought you were changing the dependency from >= 4.2 to ~> 4.2, not the other way around!

But still the travis test suite ran against 4.2.6 (that's in the Gemfile, which gets generated by schema_dev) -- you can see in the travis [log](https://travis-ci.org/SchemaPlus/schema_plus_core/jobs/123071573) or [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/123071573/log.txt) that it installed 4.2.6.  So to test against rails5 using this setup would need to first add rails 5 to schema_dev (wouldn't be hard to do, just needs doing...)

Or do you have another test somewhere that really ran against rails 5...?

**Comment by ronen** [comment]
@adamico as I mentioned over in schema_monkey, I updated schema_dev to support AR 5.0, and schema_monkey works fine with it.

With those in place, I could try out schema_plus_core on AR 5.0, and it fails.  Bummer but unsurprising.  

See the activerecord-5.0 branch, and https://travis-ci.org/SchemaPlus/schema_plus_core/builds/124089884

**Comment by adamico** [comment]
@ronen I see. The raised error is in schema_monkey, though:

```
/home/travis/.rvm/gems/ruby-2.3.0/gems/schema_monkey-2.1.4/lib/schema_monkey/active_record.rb:21:in `insert': No module ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::SchemaCreation to insert SchemaPlus::Core::ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::SchemaCreation (SchemaMonkey::InsertionError)
```

**Comment by adamico** [comment]
@ronen Ok, in the edge api page I found that the module has got a name change: 

In ActiveRecord4: ActiveRecord/ConnectionAdapters/AbstractMysqlAdapter/SchemaCreation
In ActiveRecord5: ActiveRecord/ConnectionAdapters/MySQL/SchemaCreation

**Comment by ronen** [comment]
Closing this out in light of the other work that has gotten AR 5 compatibility.

**Pull request closed without merging**
