### PR TITLE
test with supported versions of Ruby, Rails and PostgreSQL

### PR DESCRIPTION
**Pull request by ashkulz**
Depends on SchemaPlus/schema_dev#25

### CODE REVIEW

**Comment by ashkulz** [comment]
@urkle I'm not sure how to get TravisCI to run on this, like you got it working for `schema_plus_views`?

**Comment by urkle** [comment]
@ashkulz FYI I do have another developer working on updating things (see work in progress #30).  

Here is the "list" of  base changes to make for each gem

Full list of changes
* add .simplecov (see one from schema_monkey) and adjust spec/spec_helper.rb to not use simplecov gem profile
* remove all simplecov gems from gemspec
* update/add minimum ruby version to >= 2.5 in gemspec
* update schema_dev in gemspec '~> 4.1.0`
* update schema_monkey (if used) to ‘~> 3.0.0’
* update schema_core_plus (if used) to ?? (once update is ready)
* update schema_plus_compatibility (if used) to ‘~> 1.0.0’ (pending PR SchemaPlus/schema_plus_compatibility#6)
* update activerecord 
* update bundler dependency to be bare (no version specified)
* update rake to ~ 13.0.0
* update schema_dev.yml (2.5, .2.7, .3.0 and AR 5.2, 6.0, 6.1) and run `schema_dev freshen`
* remove .travis.yml
* adjust README.md top travis link to be to gh actions (see example in schema_monkey)
* separate commit with the result of  `rubocop -A --only Style/FrozenStringLiteralComment,Layout/EmptyLineAfterMagicComment,Style/Encoding`

**Comment by ashkulz** [comment]
Thanks, @urkle! I guess I'll close this PR then. Happy to see this moving along :grin:

**Comment by urkle** [comment]
@ashkulz once we get "core" updated, if you want to help working on creating PRs for the other gems you are more than welcome.

Right now the plus_core is only going to target rails 6.0 and we'll do a separate PR for 6.1 support (if you want you can start that once we release the core with AR 6.0)

For our needs we needs we'll be focusing initially on (in this order)
* schema_plus_indexes
* schema_associations
* schema_plus_columns
* schema_validations
* schema_plus_foreign_keys
* schema_plus_functions
* schema_plus_triggers
* schema_plus_views

**Pull request closed without merging**
