### PR TITLE
Rails 5.2 support

### PR DESCRIPTION
**Pull request by jeremyyap**
rails/rails@9b53f74
rails/rails@d6b779e
rails/rails@1e797e5

### CODE REVIEW

**Comment by ronen** [comment]
@jeremyyap thanks for the PR -- I'm excited to have somebody working towards getting 5.2 supported!   Your changes seem fine (dunno why the travis build failed, it seems unrelated to your changes).   But sadly there's still more to be done to get 5.2 working.  So I'm a little on the fence on merging this right now... I'm hesitant to merge changes towards 5.2 piecemeal, at least not unless they seem to fix specific tests that fail (does this?)

I've added support for 5.2 to [schema_dev](http://github.com/SchemaPlus/schema_dev), so it should be possible to bundle update (to get the latest schema_dev), then edit `schema_dev.yml` and add an entry for 5.2, then use `schema_dev bundle install --ar 5.2` and `schema_dev rspec --ar 5.2` to try it out.

Unfortunately (as I respond to most every SchemaPlus comment these days) I myself am not currently using RoR in any of my jobs and don't have the free time to delve into this myself.   (Have already spent more time on it this morning than I should!)  

But please do continue in this vein!

Cheers

**Comment by jeremyyap** [comment]
Thanks for the quick reply! I will continue to work on this using `schema_dev`, thanks for updating it.

**Comment by ronen** [comment]
Great -- and I'm happy to answer any questions or offer any advice FWIW.    Thanks!

**Comment by jeremyyap** [comment]
I believe the rails 5.0/5.1 - postgresql test failures are due to incorrect version of `pg` according to rails/rails#31671.

I've gotten all the tests to pass on my local machine by modifying `schema_dev` to restrict `pg` to `< 1`.

**Comment by ronen** [comment]
I've released 2.2.0 with your work in it.  Thanks so much!  Sorry again for the delay, for some reason I had it in my head that there was still more that needed to be done.

**Comment by jeremyyap** [comment]
Don't worry about it! Our project is blocked on several other gems with regards to upgrading Rails, so it doesn't look like we'll be on 5.2 anytime soon 😅 Thanks for all your help!

**Pull request merged**
